#!/usr/bin/env bash
# SSH client configuration

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/id_rsa
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
